"""test

Revision ID: 0211645c3042
Revises: 
Create Date: 2025-05-23 12:29:05.998559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0211645c3042'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_column', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('test_column')

    # ### end Alembic commands ###
