"""added deadline column to Task

Revision ID: 53febad50ace
Revises: 92aeb02ce601
Create Date: 2025-04-22 19:34:55.073379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53febad50ace'
down_revision = '92aeb02ce601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_column('date')
        batch_op.drop_column('data')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('deadline')

    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.VARCHAR(length=10000), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
