"""daily checked tasks

Revision ID: 70a751369e0d
Revises: 923a4f5a9f16
Create Date: 2025-05-30 15:21:02.273466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a751369e0d'
down_revision = '923a4f5a9f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_checked_tasks', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('daily_checked_tasks')

    # ### end Alembic commands ###
