"""added Plant model and necessary plant-related columns to User and Task

Revision ID: 8033480b6692
Revises: 4f2a2ca03550
Create Date: 2025-05-27 08:47:00.270803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8033480b6692'
down_revision = '4f2a2ca03550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_check', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('water_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('plant_growth', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('plant_last_watered', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('plant_last_watered')
        batch_op.drop_column('plant_growth')
        batch_op.drop_column('water_points')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('first_check')

    op.drop_table('plant')
    # ### end Alembic commands ###
