"""Added list_title column to List

Revision ID: 8b189fddc14a
Revises: 8db3d85f2828
Create Date: 2025-04-15 15:17:24.519304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b189fddc14a'
down_revision = '8db3d85f2828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_title', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_column('list_title')

    # ### end Alembic commands ###
