"""added columns related to withering logic

Revision ID: 923a4f5a9f16
Revises: 
Create Date: 2025-05-28 22:06:30.823258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923a4f5a9f16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_wither_stage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('plant_rescue_progress', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('plant_unwatered_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('plant_unwatered_days')
        batch_op.drop_column('plant_rescue_progress')
        batch_op.drop_column('plant_wither_stage')

    # ### end Alembic commands ###
