"""added if_done column to Task

Revision ID: 92aeb02ce601
Revises: 96c1a3e93fd2
Create Date: 2025-04-20 11:20:31.953715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92aeb02ce601'
down_revision = '96c1a3e93fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('if_done', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('if_done')

    # ### end Alembic commands ###
