"""modifying deadline columns in Task

Revision ID: a371c73c48e3
Revises: 53febad50ace
Create Date: 2025-04-23 14:15:50.792670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a371c73c48e3'
down_revision = '53febad50ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('deadline_time', sa.Time(), nullable=True))
        batch_op.drop_column('deadline')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.DATETIME(), nullable=True))
        batch_op.drop_column('deadline_time')
        batch_op.drop_column('deadline_date')

    # ### end Alembic commands ###
