"""modified plant model

Revision ID: d261073b6dcc
Revises: e15d08767864
Create Date: 2025-06-02 20:50:07.051367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd261073b6dcc'
down_revision = 'e15d08767864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_growth', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('final_wither_stage', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.drop_column('final_wither_stage')
        batch_op.drop_column('final_growth')

    # ### end Alembic commands ###
