"""plant withered notification column

Revision ID: e15d08767864
Revises: bb245da2e3e7
Create Date: 2025-06-01 13:33:26.332318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e15d08767864'
down_revision = 'bb245da2e3e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_withered_notification_sent', sa.Boolean(), nullable=True))
        batch_op.alter_column('plant_rescue_progress',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('plant_rescue_progress',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.drop_column('plant_withered_notification_sent')

    # ### end Alembic commands ###
